USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SMB_MARKET_INTELLIGENCE_DEV;

CREATE STAGE IF NOT EXISTS RAW.LOAD_STAGE
  COMMENT = 'Internal stage for local CSV files loaded during development';

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_HEADER_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('', 'NULL', 'null', 'NaN', 'nan')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
